## Load Data

In [96]:
import pandas as pd

df = pd.read_csv("C:/Users/vilas/Documents/0-100/AI,ML & DL/home-credit-default-risk/application_train.csv")

df.shape

(307511, 122)

## Preprocessing

In [98]:
## Null Values

df.isna().sum().sum()

9152465

In [99]:
# Filling null values of int and float dtypes

for i in df.select_dtypes(include=['int','float']).columns:
    df.fillna(df[i].median(), inplace=True)
    
# Filling null values of char dtypes

for i in df.select_dtypes(include='object').columns:
    df.fillna(df[i].value_counts().index[0], inplace=True)

In [100]:
df.isna().sum().sum()

0

In [101]:
# Label Encoding

df.select_dtypes(include='object').columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='object')

In [102]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [103]:
for i in df.select_dtypes(include='object').columns:
    df[i] = df[i].astype(str)
    le.fit(df[i])
    transformed = le.transform(df[i])
    df[i] = transformed

In [104]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,0,1,0,1,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,0,0,0,0,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,1,1,1,1,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,0,0,0,1,0,135000.0,312682.5,29686.5,...,0,0,0,0,278202.0,278202.0,278202.0,278202.0,278202.0,278202.0
4,100007,0,0,1,0,1,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

## Model Building

In [106]:
df['TARGET'].value_counts()

# We have imbalanced data

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [107]:
# First split to train and test data

X = df.drop('TARGET', axis=1)

y = df['TARGET']

In [108]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,y,test_size=0.2)

In [109]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

dt.fit(X_train,Y_train)

y_pred1 = dt.predict(X_test)

rf.fit(X_train,Y_train)

y_pred2 = rf.predict(X_test)

## Model Validation

In [111]:
from sklearn.metrics import accuracy_score, confusion_matrix

print(f"Confusion Matrix of DecisionTree Model : \n{confusion_matrix(Y_test,y_pred1)}")
print(f"Confusion Matrix of DecisionTree Model : {accuracy_score(Y_test,y_pred1):.2f}")
print(f"Accuracy of RandomForest Model :\n {confusion_matrix(Y_test,y_pred2)}")
print(f"Accuracy of RandomForest Model : {accuracy_score(Y_test,y_pred2):.2f}")

Confusion Matrix of DecisionTree Model :
[[51441  5041]
 [ 4221   800]]
Confusion Matrix of DecisionTree Model : 0.85
Accuracy of RandomForest Model :
 [[56479     3]
 [ 5017     4]]
Accuracy of RandomForest Model : 0.92

In [112]:
from sklearn.metrics import classification_report

print(f"Classification Report of DecisionTree : \n{classification_report(Y_test,y_pred1)}")
print('==========================================================')
print(f"Classification Report of Random Forest : \n{classification_report(Y_test,y_pred2)}")

Classification Report of DecisionTree :
              precision    recall  f1-score   support

           0       0.92      0.91      0.92     56482
           1       0.14      0.16      0.15      5021

    accuracy                           0.85     61503
   macro avg       0.53      0.54      0.53     61503
weighted avg       0.86      0.85      0.85     61503

==========================================================
Classification Report of Random Forest :
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     56482
           1       0.57      0.00      0.00      5021

    accuracy                           0.92     61503
   macro avg       0.74      0.50      0.48     61503
weighted avg       0.89      0.92      0.88     61503

In [113]:
new_X = df.drop('TARGET',axis=1)
new_y=df['TARGET']
new_test = pd.read_csv("C:/Users/vilas/Documents/0-100/AI,ML & DL/home-credit-default-risk/application_test.csv")

In [114]:
import seaborn as sns
import matplotlib.pyplot as plt

In [119]:
# sns.boxplot(new_test[''])

In [121]:
for i in new_test.select_dtypes(include=['int','float']).columns:
    new_test.fillna(new_test[i].median(),inplace=True)
for i in new_test.select_dtypes(include='object').columns:
    new_test.fillna(new_test[i].value_counts().index[0],inplace=True)

In [122]:
for i in new_test.select_dtypes(include='object').columns:
    new_test[i] = new_test[i].astype(str)

    le.fit(new_test[i])
    transformed = le.transform(new_test[i])
    new_test[i] = transformed

In [123]:
new_test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,0,0,0,1,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,0,1,0,1,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,0,1,1,1,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,0,0,0,1,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,0,1,1,0,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,277549.0,277549.0,277549.0,277549.0,277549.0,277549.0

In [128]:
new_X = df.drop('TARGET',axis=1)
new_y=df['TARGET']

dt.fit(new_X,new_y)
new_pred = dt.predict(new_test)

# print(accuracy_score(Y_test,new_pred))
print("Train Shape:", new_X.shape)
print("Test Shape :", new_test.shape)

print("TARGET in train:", 'TARGET' in df.columns)
print("TARGET in test :", 'TARGET' in new_test.columns)

Train Shape: (307511, 121)
Test Shape : (48744, 121)
TARGET in train: True
TARGET in test : False