In [2]:
import pandas as pd

df = pd.read_csv(r'ai_student_impact_dataset (1).csv')

df.shape

(50000, 16)

In [4]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium

In [8]:
df.isna().sum().sum()

0

In [12]:
df.duplicated().sum()

0

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str)

    le.fit(df[col])

    trans = le.transform(df[col])
    df[col] = trans

In [20]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,2,3,2.418,23.31,0,1,1,True,8.13,5,1,6,2.393,86.44,0
1,100002,3,2,3.821,1.12,3,0,5,False,16.65,3,1,9,3.696,69.39,1
2,100003,1,0,3.398,21.26,4,1,2,False,10.35,5,2,9,3.499,73.93,2
3,100004,1,3,3.789,1.82,0,2,4,False,15.23,2,1,2,4.000,63.58,2
4,100005,4,4,3.635,9.29,1,0,4,False,12.55,4,1,4,3.798,100.00,2

In [24]:
df['Paid_Subscription'] = le.fit_transform(df['Paid_Subscription'])

In [26]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,2,3,2.418,23.31,0,1,1,1,8.13,5,1,6,2.393,86.44,0
1,100002,3,2,3.821,1.12,3,0,5,0,16.65,3,1,9,3.696,69.39,1
2,100003,1,0,3.398,21.26,4,1,2,0,10.35,5,2,9,3.499,73.93,2
3,100004,1,3,3.789,1.82,0,2,4,0,15.23,2,1,2,4.000,63.58,2
4,100005,4,4,3.635,9.29,1,0,4,0,12.55,4,1,4,3.798,100.00,2

In [28]:
x = df.drop('Burnout_Risk_Level', axis=1)
y = df['Burnout_Risk_Level']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

l = [dt,rf]

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score

for i in l:
    i.fit(x_train,y_train)
    y_pred = i.predict(x_test)

    print(f"Confusion Matrix of {i.__class__.__name__} :\n{confusion_matrix(y_test,y_pred)}")
    print(f"Accuracy Score of {i.__class__.__name__} :\n{accuracy_score(y_test,y_pred):.2f}")
    print()

Confusion Matrix of DecisionTreeClassifier :
[[1090  490  956]
 [ 459 1382 1428]
 [ 937 1417 1841]]
Accuracy Score of DecisionTreeClassifier :
0.43

Confusion Matrix of RandomForestClassifier :
[[1187  280 1069]
 [ 103 1540 1626]
 [ 484 1254 2457]]
Accuracy Score of RandomForestClassifier :
0.52