# Setting up Project

Import Required Libraries 👇🏼

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [42]:
df=pd.read_csv('bank.csv',header=0,sep=';')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [46]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

In [48]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [50]:
df.shape

(4521, 17)

In [52]:
# Displaying all the fields/columns

print(list(df.columns))

['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

In [54]:
# Eliminating Unwanted Fields
#drop columns which are not needed.

df.drop(df.columns[[0, 3, 5, 8, 9, 10, 11, 12, 13, 14]], axis = 1, inplace = True)

In [56]:
df.head()

           job  marital default housing loan poutcome   y
0   unemployed  married      no      no   no  unknown  no
1     services  married      no     yes  yes  failure  no
2   management   single      no     yes   no  failure  no
3   management  married      no     yes  yes  unknown  no
4  blue-collar  married      no     yes   no  unknown  no

In [60]:
# Encoding the data

data = pd.get_dummies(df,columns=['job','marital','default','housing','loan','poutcome'])

In [62]:
data.head()

,y,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,...,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,no,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,False,False,False,True
1,no,False,False,False,False,False,False,False,True,False,...,True,False,False,True,False,True,True,False,False,False
2,no,False,False,False,False,True,False,False,False,False,...,True,False,False,True,True,False,True,False,False,False
3,no,False,False,False,False,True,False,False,False,False,...,True,False,False,True,False,True,False,False,False,True
4,no,False,True,False,False,False,False,False,False,False,...,True,False,False,True,True,False,False,False,False,True

In [66]:
data.columns

Index(['y', 'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'marital_divorced', 'marital_married', 'marital_single',
       'default_no', 'default_yes', 'housing_no', 'housing_yes', 'loan_no',
       'loan_yes', 'poutcome_failure', 'poutcome_other', 'poutcome_success',
       'poutcome_unknown'],
      dtype='object')

In [68]:
data

,y,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,...,default_no,default_yes,housing_no,housing_yes,loan_no,loan_yes,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,no,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,False,False,False,True
1,no,False,False,False,False,False,False,False,True,False,...,True,False,False,True,False,True,True,False,False,False
2,no,False,False,False,False,True,False,False,False,False,...,True,False,False,True,True,False,True,False,False,False
3,no,False,False,False,False,True,False,False,False,False,...,True,False,False,True,False,True,False,False,False,True
4,no,False,True,False,False,False,False,False,False,False,...,True,False,False,True,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,no,False,False,False,False,False,False,False,True,False,...,True,False,False,True,True,False,False,False,False,True
4517,no,False,False,False,False,False,False,True,False,False,...,False,True,False,True,False,True,False,False,False,True
4518,no,False,False,False,False,False,False,False,False,False,...,True,False,True,False,True,False,False,False,False,True
4519,no,False,True,False,False,False,False,False,False,False,...,True,False,True,False,True,False,False,True,False,False
4520,no,False,False,True,False,False,False,False,False,False,...,True,False,False,True,False,True,False,True,False,False

In [70]:
data.drop(data.columns[[12, 16, 18, 21, 24]], axis=1, inplace=True)

In [72]:
data.columns

Index(['y', 'job_admin.', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'marital_divorced', 'marital_married', 'marital_single', 'default_yes',
       'housing_yes', 'loan_no', 'poutcome_failure', 'poutcome_other',
       'poutcome_unknown'],
      dtype='object')

In [74]:
# Splitting Data

X = data.iloc[:,1:]
X.head()

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,marital_divorced,marital_married,marital_single,default_yes,housing_yes,loan_no,poutcome_failure,poutcome_other,poutcome_unknown
0,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,True
1,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,True,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,True,True,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True
4,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,False,False,True

In [80]:
y = data.iloc[:,0]
y.head()

0    no
1    no
2    no
3    no
4    no
Name: y, dtype: object

In [82]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,random_state=0)

In [84]:
classifier = LogisticRegression(solver='lbfgs',random_state=0)

In [86]:
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [88]:
predicted_y = classifier.predict(X_test)

In [90]:
predicted_y

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [92]:
for x in range(len(predicted_y)):
   if (predicted_y[x] == 'yes'):
      print(x, end="\t")

45	108	223	265	357	401	538	566	617	654	671	701	871	885	909	925	1056	1087

In [94]:
classifier.score(X_test,Y_test)

0.8903625110521662