In [30]:
import pandas as pd

df = pd.read_csv(r'student_dataset_10000_rows.csv')

df.shape

(10000, 8)

In [32]:
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [34]:
# Label Encoding

df.select_dtypes(include='object').columns

Index(['placement_status'], dtype='object')

In [10]:
df.isna().sum().sum()

0

In [14]:
df.duplicated().sum()

0

In [36]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['placement_status']=le.fit_transform(df['placement_status'])

In [38]:
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,1
1,4,69,5,3,8,56,100.00,1
2,11,60,7,6,10,45,100.00,1
3,8,99,9,8,4,55,90.17,1
4,5,52,8,6,8,40,78.82,1

In [20]:
df['placement_status'].value_counts()

placement_status
1    8356
0    1644
Name: count, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

x = df.drop('placement_status', axis=1)
y = df['placement_status']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify = y)

In [40]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

dt.fit(x_train,y_train)
y_pred1 = dt.predict(x_test)

rf.fit(x_train,y_train)
y_pred2 = rf.predict(x_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print(f"Confusion Matrix of Decision Tree model : \n{confusion_matrix(y_test,y_pred1)} ")
print(f'\n Accuracy of Decision Tree Model : {accuracy_score(y_test,y_pred1):.2f}\n')
print(f"Confusion Matrix of Random Forest model : \n{confusion_matrix(y_test,y_pred2)} \n")
print(f'\n Accuracy of Random Forest Model : {accuracy_score(y_test,y_pred2):.2f}')

Confusion Matrix of Decision Tree model :
[[ 329    0]
 [   0 1671]]

 Accuracy of Decision Tree Model : 1.00

Confusion Matrix of Random Forest model :
[[ 329    0]
 [   0 1671]]


 Accuracy of Random Forest Model : 1.00